### ISSUE TITLE
Error with HTTPPOST request

### ISSUE THREAD

**Issue by fmaille** [akunzai/GSS.Authentication.CAS#1]
Hello,

I'm using this api in order to use the cas authentication. All works fine except the HTTP Post request.
Indeed, when i'm making a post request, I always have this error :

![image](https://cloud.githubusercontent.com/assets/28933923/26421544/b6018398-40c6-11e7-83d0-f94e77f2502f.png)

Is this a bug ?

Thanks per advance.

**Comment by fmaille** [comment]
Hello,

This bug is correct by changing the invoke method of CasSingleSignOutMiddleware.cs by :

 public async Task Invoke(HttpContext context)
        {
            if (context.Request.Method.Equals(HttpMethod.Post.Method, StringComparison.OrdinalIgnoreCase))
            {
                var formData = await context.Request.ReadFormAsync(context.RequestAborted).ConfigureAwait(false);

				**if (formData.Keys.Contains("logoutRequest"))
				{**
					var logOutRequest = formData.FirstOrDefault(x => x.Key == "logoutRequest").Value[0];
					if (!string.IsNullOrEmpty(logOutRequest))
					{
						logger.LogDebug($"logoutRequest: {logOutRequest}");
						var serviceTicket = ExtractSingleSignOutTicketFromSamlResponse(logOutRequest);
						if (!string.IsNullOrEmpty(serviceTicket))
						{
							logger.LogInformation($"remove serviceTicket: {serviceTicket} ...");
							await store.RemoveAsync(serviceTicket);
						}
					}
				}
            }
            await next.Invoke(context);
        }

**Comment by akunzai** [comment]
Thanks for your report, [fix](https://github.com/akunzai/GSS.Authentication.CAS/commit/4f9152ddaa062e79356eeed7285cfefb7d1731dc) applied.

you can update version to [1.2.0](https://www.nuget.org/packages/GSS.Authentication.CAS.AspNetCore/) on nuget now

**Comment by akunzai** [comment]
close issue
