### ISSUE TITLE
Strong named assemblies

### ISSUE THREAD

**Issue by Galad** [akunzai/GSS.Authentication.CAS#15]
Hello,
Would you consider signing the assemblies in order to give them a strong name ?

Microsoft published an article about signing open-source assemblies: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

Thanks

**Comment by akunzai** [comment]
Hi @Galad, thanks for your reminder.

I will consider it.

**Comment by akunzai** [comment]
closed by #16
