### ISSUE TITLE
Skip middle page in .net core 7

### ISSUE THREAD

**Issue by mspace23** [akunzai/GSS.Authentication.CAS#298]
Hello, 
I would like to ask how can we skip the middle page which displays the
"Register
Associate your CAS account." message

I use .net core 7

thank you

**Comment by akunzai** [comment]
Please provide me with more details so that I can reproduce your problem. 

Including the source code and screen recording.

**Comment by mspace23** [comment]
Thank you for your response!

In my program.cs I have:

builder.Services.AddAuthentication()
    .AddCAS(options =>
    {
        options.CasServerUrlBase = builder.Configuration["Authentication:CAS:ServerUrlBase"];
        options.CallbackPath = "/Home/Test";

        var protocolVersion = builder.Configuration.GetValue("Authentication:CAS:ProtocolVersion", 3);
        if (protocolVersion != 3)
        {
            options.ServiceTicketValidator = protocolVersion switch
            {
                1 => new Cas10ServiceTicketValidator(options),
                2 => new Cas20ServiceTicketValidator(options),
                _ => null
            };
        }

        options.Events.OnCreatingTicket = context =>
        {
            if (context.Identity == null)
                return Task.CompletedTask;

            // Map claims from assertion
            var assertion = context.Assertion;
            context.Identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, assertion.PrincipalName));
            if (assertion.Attributes.TryGetValue("display_name", out var displayName))
            {
                context.Identity.AddClaim(new Claim(ClaimTypes.Name, displayName));
            }

            if (assertion.Attributes.TryGetValue("email", out var email))
            {
                context.Identity.AddClaim(new Claim(ClaimTypes.Email, email));
            }

            return Task.CompletedTask;
    };
    });

When I try to login it asks for email

Register
Associate your CAS account.
You've successfully authenticated with CAS. Please enter an email address for this site below and click the Register button to finish logging in.

thank you

**Comment by akunzai** [comment]
You needs to customize the [Account/ExternalLogin](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/ExternalLogin.cshtml) page or the [Account/ExternalLogin#OnGetCallbackAsync](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/ExternalLogin.cshtml.cs#L126) function of [Scaffold Identity](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity) in ASP.NET Core project.

That's not part of this authentication middleware. I'm closing this issue.

## Reference

- https://github.com/dotnet/aspnetcore/issues/25029
