### ISSUE TITLE
Nuget Installation Problem

### ISSUE THREAD

**Issue by raizarachi** [akunzai/GSS.Authentication.CAS#3]
Hello,

since your last modifications (thank you for them, by the way) I cannot install the 2.1.0 version of GSS.Authentication.CAS.Owin, because it seeks a version of GSS.Authentication.CAS.Core superior to 2.0.1 (which doesn't exists).

Best regards.

**Comment by akunzai** [comment]
Hi @raizarachi,

thanks for your feedback.

I have pushed a matched version of GSS.Authentication.CAS.Core on nuget.org.

**Comment by akunzai** [comment]
closed by https://www.nuget.org/packages/GSS.Authentication.CAS.Core/
