### ISSUE TITLE
Exception: There was a problem validating ticket.

### ISSUE THREAD

**Issue by Wangzw-Git** [akunzai/GSS.Authentication.CAS#4]
When this method is executed “HttpContext.ChallengeAsync();“

An unhandled exception occurred while processing the request.
Exception: There was a problem validating ticket.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
![qq 20180517111530](https://user-images.githubusercontent.com/17921667/40154933-acdf3c3a-59c3-11e8-81fd-e717fe86c501.png)
Please help me, thanks

**Comment by akunzai** [comment]
Hi @Wangzw-Git,

You should check the warning logger message for details.

the source code: https://github.com/akunzai/GSS.Authentication.CAS/blob/master/src/GSS.Authentication.CAS.AspNetCore/CasAuthenticationHandler.cs#L79

**Comment by akunzai** [comment]
Hi @Wangzw-Git 

[CallbackPath](https://github.com/aspnet/Security/blob/f8b4f4c620e2faaeec262d302df143068c8d0b33/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs#L90) will be process by middleware, do't need to add it,

If your are running the sample project,
Please modify the `example.com` in appsettings.json to your `REAL CAS Server Host`
or add [environment configurations](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.0&tabs=basicconfiguration#configuration-by-environment) to override it.

**Comment by Wangzw-Git** [comment]
It has been modified
Can you normally run the sample project at netcore2.0.6?

**Comment by akunzai** [comment]
The default behavior of service-ticket validation was using [CAS Protocol Specification](https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol-Specification.html) 3.0 implementation (Cas30ServiceTicketValidator),

If your CAS Server does not support that, your will need to configure alternative ServiceTicketValidator implementation in AddCAS options. 

for example:
```csharp
.AddCAS(options =>
{
  ...
  options.ServiceTicketValidator = new GSS.Authentication.CAS.Validation.Cas20ServiceTicketValidator(
  new GSS.Authentication.CAS.CasOptions
  {
    CasServerUrlBase = Configuration["Authentication:CAS:CasServerUrlBase"]
  });
  ...
})
```

**Comment by Wangzw-Git** [comment]
Great.
The problem was solved perfectly
thank you very much!!!
