### ISSUE TITLE
Always redirects to root instead of base path

### ISSUE THREAD

**Issue by PascalTurbo** [akunzai/GSS.Authentication.CAS#43]
We've build an app like the example "ASP.NET Core app with Single-Sign-Out". But it's running behind a reverse proxy in a subfolder. 

The basePath is set like

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UsePathBase("/base");
    app.UsePathBase("/base");
    ...
}
```

All other parts of the app are working like excepted but after login it should redirect to `www.myserver.com/base` but does redirect to `www.myserver.com/`

**Comment by akunzai** [comment]
@PascalTurbo you can specified the [AuthenticationProperties.RedirectUri](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.http.authentication.authenticationproperties.redirecturi) during Challenge.

```diff
- return Challenge(new AuthenticationProperties { RedirectUri = "/" }, scheme);
+ return Challenge(new AuthenticationProperties { RedirectUri = "/base" }, scheme);
```

**Comment by PascalTurbo** [comment]
@akunzai : Thank you for your fast support.
