### ISSUE TITLE
attributes missing  after deserialize

### ISSUE THREAD

**Issue by cjdxhjj** [akunzai/GSS.Authentication.CAS#5]
Assertion Attribute value is StringValues, get stored json from cache is ok, but when deserialize is missing,can you replace string insted?

**Comment by akunzai** [comment]
Thanks for your report, issue should be fixed by apply custom JSON converter to read JSON.

you can update [GSS.Authentication.CAS.Core](https://www.nuget.org/packages/GSS.Authentication.CAS.Core/2.1.2) on nuget to solve this problem.

**Comment by akunzai** [comment]
close
