### ISSUE TITLE
SingleSignOut ReadFormAsync error

### ISSUE THREAD

**Issue by cjdxhjj** [akunzai/GSS.Authentication.CAS#6]
when site provide json request, client send content-type=application/json, the middleware will cause a error, it need futher judge
`if (context.Request.Method.Equals(HttpMethod.Post.Method, StringComparison.OrdinalIgnoreCase) && context.Request.ContentType.Equals("application/x-www-form-urlencoded", StringComparison.InvariantCulture))`

and futher more, when app is cluster the function may not working, I provider a function to return a ip and point list to return the all nodes, exclude the localnode, I also send the message to other node,
`namespace Cas.Authentication.AspNetCore
{
    public class SingleSignOutOptions
    {
        public SingleSignOutOptions()
        {
            LoginPath = new PathString("/cas-login");
            LogoutPath = new PathString("/cas-logout");
        }

        public string CasBaseUrl { get; set; }
        public PathString LoginPath { get; set; }

        public PathString LogoutPath { get; set; }

        public IClusterNodeDiscover NodeDiscover { get; set; }
    }
}

public interface IClusterNodeDiscover
    {
        IList<string> GetAllNodes();
    }`

it may read nodes from consul or zk

in this middleware I also provider the signin and signout endpoint
`else if(context.Request.Path.StartsWithSegments(_signOutOptions.LoginPath))
            {
                await context.ChallengeAsync(CasDefaults.AuthenticationType, new AuthenticationProperties { RedirectUri = context.Request.Query["ReturnUrl"] });
                return;
            }
            else if(context.Request.Path.StartsWithSegments(_signOutOptions.LogoutPath))
            {
                await context.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                context.Response.Redirect($"{_signOutOptions.CasBaseUrl}/logout?service={Uri.EscapeDataString(context.Request.Scheme + "://" + context.Request.Host)}");
                return;
            }`

for session store, I provider a simple wapper to support IDistributedCache and IMemoryCache, any implement can use, did not need to reference an dll
`.AddCas(new MemoryCache(Options.Create(new MemoryCacheOptions())), null,...;`

**Comment by akunzai** [comment]
Thanks for your report, [fix](https://github.com/akunzai/GSS.Authentication.CAS/commit/9c56c0a5d00bfa77b1017e8f9d1688a440fa9a4b) applied.

For cluster issue, maybe you can solve it by using other distributed cache implementation that can cross process (for example: [Microsoft.Extensions.Caching.Redis](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/)),
if it can't be solved, please fire another issue, and provide more test-case code and details, thanks. :)

**Comment by cjdxhjj** [comment]
yes, the issure occur when use local memory cache, that could solved by using redis store

**Comment by akunzai** [comment]
close issue
