### ISSUE TITLE
GSS.Authentication.CAS.Owin CasSingleSignOutMiddleware does not support null ContentType

### ISSUE THREAD

**Issue by ahmadh21** [akunzai/GSS.Authentication.CAS#68]
I have a ASP.NET Web API project using OWIN authentication. We do not always set the ContentType when doing post. It looks like there is a check on line 34 that breaks when ContentType is null.

https://github.com/akunzai/GSS.Authentication.CAS/blob/2c7c683319c1aeb7aa6aa77c86611bee81f1116c/src/GSS.Authentication.CAS.Owin/CasSingleSignOutMiddleware.cs#L34

**Comment by akunzai** [comment]
Hi @ahmadh21 ,

Thanks for reporting this issue.

new version of GSS.Authentication.CAS.Owin is [released](https://www.nuget.org/packages/GSS.Authentication.CAS.Owin/).
