### ISSUE TITLE
Single Sign-Out for cluster-based applications

### ISSUE THREAD

**Issue by shshshdy** [akunzai/GSS.Authentication.CAS#8]
先登录A站点，再登录B站点，退出A站点，B站点未退出
First login A site, then log on to B site, exit A site, B site did not quit.

**Comment by akunzai** [comment]
For cluster issue, you can solve it by using other distributed cache implementation that can cross process (for example: Microsoft.Extensions.Caching.Redis)

**Comment by shshshdy** [comment]
thankyou
