### ISSUE TITLE
netcore 2.1 web api usage

### ISSUE THREAD

**Issue by mspasiuk** [akunzai/GSS.Authentication.CAS#9]
How can implement your library with the next scenario.
Angular 6 app.
Net Core 2.1 web api sln.

I can assume that the angular app will do the auth against CAS.
Does the Angular should add something to the header in the requests?

I got this working with my web api, using a browser as a client, but for example If I use postman I don't get results, maybe because I'm being redirected to CAS login page. And the same will happen with the Angular app as the client.

Thanks

**Comment by akunzai** [comment]
For security reason, maybe it was not a good idea to use browser as a CAS client.

[CAS protocol](https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html) was strongly relay on HTTP redirect, and the browser will ALWAYS follow HTTP redirection.

browser based apps maybe should simply relay on encrypted cookies that issued by your application backend (backend acting as a CAS client)

If you insist to use browser as a Authenticator, maybe take a look of theses:
- [OAuth protocol](https://apereo.github.io/cas/5.2.x/installation/OAuth-OpenId-Authentication.html)
- [REST Protocol](https://apereo.github.io/cas/5.2.x/protocol/REST-Protocol.html)

**Comment by akunzai** [comment]
For security reasons, using a browser as a CAS client may not be a good idea.

The [CAS protocol](https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html) strongly relies on HTTP redirection, and browsers ALWAYS follow HTTP redirection.

It is recommended that browser-based applications should simply use the encrypted cookies issued by the backend application (acting as a CAS client).

But if you insist to use browser as a Authenticator to communicate directly with CAS server:

- [OAuth Protocol](https://apereo.github.io/cas/5.2.x/protocol/OAuth-Protocol.html)
- [REST Protocol](https://apereo.github.io/cas/5.2.x/protocol/REST-Protocol.html)

Hope this helps

**Comment by akunzai** [comment]
For security reasons, using a browser as a CAS client may not be a good idea.

The [CAS protocol](https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html) strongly relies on HTTP redirection, and browsers ALWAYS follow HTTP redirection.

It is recommended that browser-based applications should simply use the encrypted cookies issued by the backend application (acting as a CAS client).

But if you insist to use browser as a Authenticator to communicate directly with CAS server:

- [OAuth Protocol](https://apereo.github.io/cas/5.2.x/protocol/OAuth-Protocol.html)
- [REST Protocol](https://apereo.github.io/cas/5.2.x/protocol/REST-Protocol.html)

Hope this helps

**Comment by akunzai** [comment]
For security reasons, using a browser as a CAS client may not be a good idea.

The [CAS protocol](https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html) strongly relies on HTTP redirection, and browsers ALWAYS follow HTTP redirection.

It is recommended that browser-based applications should simply use the encrypted cookies issued by the backend application (acting as a CAS client).

But if you insist to use browser as a Authenticator to communicate directly with CAS server:

- [OAuth Protocol](https://apereo.github.io/cas/5.2.x/protocol/OAuth-Protocol.html)
- [REST Protocol](https://apereo.github.io/cas/5.2.x/protocol/REST-Protocol.html)

Hope this helps

**Comment by mspasiuk** [comment]
Thanks I finally got it work as expected.
Next step, is to integrate with asp net core identity so I can use [Authorize] filter with roles. I will store roles for each user on my db (AspNetRoles and AspNetUserRoles tables, and after succesfull login, check if the user has the role).
CAS only returns the username, no other claims.

**Comment by akunzai** [comment]
that is CAS middleware default behavior,
you can get more claims by register the OnCreatingTicket event.

```csharp
options.Events = new CasEvents
            {
                OnCreatingTicket = context =>
                {
                    // add claims from CasIdentity.Assertion ?
                    var assertion = context.Assertion;
                    if (assertion == null) return Task.CompletedTask;
                    if (!(context.Principal.Identity is ClaimsIdentity identity)) return Task.CompletedTask;
                    identity.AddClaim(new Claim(identity.NameClaimType, assertion.PrincipalName));
                    if (assertion.Attributes.TryGetValue("email", out var email))
                    {
                        identity.AddClaim(new Claim(ClaimTypes.Email, email));
                    }
                    if (assertion.Attributes.TryGetValue("display_name", out var displayName))
                    {
                        identity.AddClaim(new Claim(ClaimTypes.GivenName, displayName));
                    }
                    return Task.CompletedTask;
                }
            };
```
